chains_mapping = {
    "XYM": "XYM",
    "XRP": "XRP",
    "POLKADOT": "POLKADOT",
    "XAVAX": "X-CHAIN",
    "Fantom(FTM)": "FANTOM",
    "Dogecoin(DOGE)": "DOGE",
    "Arbitrum One(ARB-Bridged)": "ARBITRUM",
    "NEM": "NEM",
    "BNB": "BEP20",
    "TRX": "TRC20",
    "SOL": "SOL",
    "C-Chain": "C-CHAIN",
    "Klaytn": "KLAYTN",
    "CAP20": "CAP20",
    "Polygon(MATIC-Bridged)": "POLYGON",
    "TERRA_CLASSIC": "TERRA_CLASSIC",
    "MATIC.E": "POLYGON",
    "Polygon": "POLYGON",
    "ADA": "CARDANO",
    "QTUM": "QTUM",
    "Tron(TRC20)": "TRC20",
    "Fantom": "FANTOM",
    "ArbitrumOne": "ARBITRUM",
    "Arbitrum One(ARB)": "ARBITRUM",
    "FTM": "FANTOM",
    "ENJ": "ENJ",
    "LUNC": "LUNC",
    "EGLD": "ELROND",
    "ETH": "ERC20",
    "OP": "OPTIMISM",
    "MATIC": "POLYGON",
    "Ravencoin(RVN)": "RVN",
    "XTZ": "XTZ",
    "ARBI": "ARBITRUM",
    "Kusama": "KUSAMA",
    "MANTLE": "MANTLE",
    "BEP20": "BEP20",
    "Polygon(MATIC)": "POLYGON",
    "BCH": "BCH",
    "ERC20": "ERC20",
    "FANTOM": "FANTOM",
    "ALGO": "ALGO",
    "X-Chain": "X-CHAIN",
    "DOGE": "DOGE",
    "EOS": "EOS",
    "Internet Computer(ICP)": "ICP",
    "ZEN": "ZEN",
    "THETA": "THETA",
    "WEMIX": "WEMIX",
    "BSC": "BEP20",
    "COSMOS": "COSMOS",
    "Ethereum(ERC20)": "ERC20",
    "ZKSYNC": "ZKSYNC",
    "ICP": "ICP",
    "LTC": "LTC",
    "Bitcoin Cash(BCH)": "BCH",
    "CAVAX": "C-CHAIN",
    "DCR": "DCR",
    "AVAX-C": "C-CHAIN",
    "FIL": "FIL",
    "Litecoin(LTC)": "LTC",
    "TRC20": "TRC20",
    "ETC": "ETC",
    "THORChain": "THORCHAIN",
    "Cardano": "CARDANO",
    "Elrond": "ELROND",
    "Klaytn(KLAY)": "KLAYTN",
    "Avalanche C Chain(AVAX CCHAIN)": "C-CHAIN",
    "Ethereum Classic(ETC)": "ETC",
    "Solana(SOL)": "SOL",
    "RVN": "RVN",
    "Cardano(ADA)": "CARDANO",
    "ARBITRUM": "ARBITRUM",
    "WAVES": "WAVES",
    "LUNA": "LUNA",
    "POLYGON": "POLYGON",
    "ONE": "ONE",
    "Avalanche X Chain(AVAX XCHAIN)": "X-CHAIN",
    "KLAY": "KLAY",
    "Stellar(XLM)": "XLM",
    "RONIN": "RONIN",
    "Ripple(XRP)": "XRP",
    "HECO": "HECO",
    "HARMONY": "HARMONY",
    "Optimism(OP)": "OPTIMISM",
    "WEMIXMainnet": "WEMIX",
    "XLM": "XLM",
    "KSM": "KUSAMA",
    "StellarLumens": "XLM",
    "OPTIMISM": "OPTIMISM",
    "Optimism(OP-Bridged)": "OPTIMISM",
    "Harmony": "HARMONY",
    "ATOM": "ATOM",
    "KLAYTN": "KLAYTN",
    "OP.E": "OPTIMISM",
    "ARBI.E": "ARBITRUM",
    "Cosmos(ATOM)": "COSMOS",
    "Terra": "TERRA",
    "Polkadot(DOT)": "POLKADOT",
    "Symbol": "SYMBOL",
    "DOT": "POLKADOT",
    "Algorand(ALGO)": "ALGO",
    "BNB Beacon Chain(BEP2)": "BEP2",
}
